use quanlimayin

INSERT INTO Users (UserName , Password , Role)
values 
('admin' , 'admin' , 'admin'),
('thuha','thuha', 'user'),
('quocanh','anh', 'user'),
('khoi','khoi', 'user'),
('hieu','hieu', 'user');

INSERT INTO Category (Description, ImgUri, CategoryName) VALUES
(N'Máy in laser là một loại máy in kỹ thuật số, hoạt động dựa trên quy trình xerography. Quy trình này sử dụng tia laser để tạo ra ảnh quang điện theo từng dòng in, sau đó đưa lên đối tượng in. Máy in laser sử dụng tia laser để chiếu lên trống từ, khi trống từ quay qua ống mực, mực sẽ được hút vào giấy. Giấy sau đó được đưa qua trống và mực bám vào giấy. Cuối cùng, giấy sẽ được sấy khô để đảm bảo mực được bám chắc vào giấy in. So với máy in thông thường, máy in laser có tốc độ in vượt trội hơn nhiều. ', 'https://huyyyy.sirv.com/printer/category/mayinlazer.webp', N'Máy in Laser'),
(N'Máy in phun màu hoạt động theo cơ chế đặc biệt, khi nhận lệnh in, máy tự động xử lý tín hiệu và tiếp theo đó, phun các hạt mực màu lên vật liệu in. Kết quả là sự hình thành của văn bản và hình ảnh.', 'https://huyyyy.sirv.com/printer/category/mayinphun1.webp', 'Máy in phun');
insert into Product(ProductName, Brand , Description , Img , Price , InStock ,Ram , SizePage , CategoryId)
values (N'Máy in Brother DCP-T820DW', N'Brother' , N'Máy in Brother DCP-T820DW là dòng sản phẩm cao cấp hỗ trợ người dùng in ấn với khối lượng in lớn mà vẫn đảm bảo hiệu quả và tiết kiệm chi phí. Nếu có nhu cầu mua sắm thiết bị in mới cho gia đình hoặc văn phòng thì bạn có thể tham khảo qua máy in Brother DCP-T820DW chất lượng, với nhiều tính năng nổi bật. ' , 'https://huyyyy.sirv.com/printer/products/brother_dcpt820.webp', 8990000,100,2,N'A4' ,1),
(N'Máy in laser trắng đen BROTHER HL-L2321D' ,N'Brother' ,  N'Hiện nay nhu cầu in ấn trong môi trường doanh nghiệp ngày càng tăng cao. Để đáp ứng yêu cầu này, Brother, thương hiệu nổi tiếng về thiết bị văn phòng, đã cho ra mắt máy in Brother HL-L2321D – một giải pháp in ấn đơn sắc mạnh mẽ, đáng tin cậy và tiết kiệm chi phí, được thiết kế đặc biệt cho các doanh nghiệp vừa và nhỏ.' , 'https://huyyyy.sirv.com/printer/products/borther1.webp', 3290000,100,2,N'A4' ,1),
(N'Máy in Brother DCP-T226 (Trắng)' , N'Brother' , N'Máy in Brother DCP-T226 (Trắng) là một trong những lựa chọn hàng đầu cho các văn phòng hiện đại, nơi mà nhu cầu in ấn tài liệu cơ bản ngày càng tăng cao. Với thiết kế tinh tế, tính năng đa dạng in, copy, scan và hiệu suất ổn định, máy in này đáp ứng tốt các yêu cầu in ấn, mang lại sự tiện lợi và hiệu quả trong công việc hàng ngày.' , 'https://huyyyy.sirv.com/printer/products/borther_dcp.webp', 3390000,100,2,N'A4' ,1),
(N'Máy in laser trắng đen BROTHER MFC-L2701DW' ,N'Brother' ,  N'Máy in laser trắng đen BROTHER MFC-L2701DW là thiết bị đa chức năng, tích hợp đầy đủ các tính năng như in, copy, scan và fax, giúp đáp ứng mọi nhu cầu văn phòng chỉ trong một thiết bị nhỏ gọn. Với khả năng kết hợp nhiều công dụng, chiếc máy này giúp tối ưu hóa không gian làm việc và tiết kiệm chi phí đầu tư thiết bị.' , 'https://huyyyy.sirv.com/printer/products/brother_mfc.webp', 3390000,100,4,N'A4' ,1),
(N'Máy in laser màu BROTHER MFC-L8690CDW' ,N'Brother' ,  N'Máy in laser màu BROTHER MFC-L8690CDW được sản xuất bởi hãng Brother, 1 tập đoàn công nghệ nổi tiếng thế giới của Nhật Bản đã khẳng định được vị trí của mình trong nhiều năm qua.Máy in laser màu BROTHER MFC-L8690CDW phù hợp cho các văn phòng, cửa hàng photo vì hiệu suất và chất lượng cao.Được trang bị nhiều chức năng như in, sao chép, fax, scan, wifi,… cho thiết bị trở nên vô cùng đa năng và thuận tiện cho nhiều mục đích sử dụng khác nhau của người dùng.' , 'https://huyyyy.sirv.com/printer/products/brother_mfc1.webp', 16100000,100,8,N'A4' ,2),
(N'Máy in Canon PIXMA TS207'  ,N'Canon' ,  N'Canon PIXMA TS207 là loại máy in văn phòng đáp ứng nhu cầu in ấn, phun màu một cách hiệu quả cho người dùng. Với thiết kế tinh tế và hiệu suất ổn định, loại máy này sẽ cung cấp chất lượng bản in một cách rõ nét. Máy in nổi bật với các tính năng in tài liệu,  mang đến hình ảnh rõ ràng, chi tiết đáp ứng nhu cầu đa dạng. Cách sử dụng loại máy in này cũng rất đơn giản và tiện lợi. ' , 'https://huyyyy.sirv.com/printer/products/brother_mfc.webp', 3390000,100,4,N'A4' ,2),
(N'Máy in Canon PIXMA TS207'  ,N'Canon' ,  N'Canon PIXMA TS207 là loại máy in văn phòng đáp ứng nhu cầu in ấn, phun màu một cách hiệu quả cho người dùng. Với thiết kế tinh tế và hiệu suất ổn định, loại máy này sẽ cung cấp chất lượng bản in một cách rõ nét. Máy in nổi bật với các tính năng in tài liệu,  mang đến hình ảnh rõ ràng, chi tiết đáp ứng nhu cầu đa dạng. Cách sử dụng loại máy in này cũng rất đơn giản và tiện lợi. ' , 'https://huyyyy.sirv.com/printer/products/brother_mfc.webp', 3390000,100,4,N'A4' ,2);